# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/"

[main.params]
icon = "home"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Phosphorescentt"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/EsportsPhos"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "ko-fi"
name = "Ko-fi"
url = "https://ko-fi.com/phosphorescent"

[social.params]
icon = "link"